export default [
    "Stratocaster",
    "Telecaster",
    "Les Paul",
    "SG Standard",
    "Super Strat",
    "Jazzmaster",
    "Explorer",
    "Flying V",
    "Dreadnought",
    "Parlor Guitar",
    "Tube Combo Amp",
    "Solid State Amp",
    "Mini Practice Amp",
    "Modeling Amp",
    "Cabinet 2x12",
    "Cabinet 4x12",
    "Overdrive Pedal",
    "Distortion Pedal",
    "Fuzz Pedal",
    "Chorus Pedal",
    "Phaser Pedal",
    "Flanger Pedal",
    "Tremolo Pedal",
    "Delay Pedal",
    "Reverb Pedal",
    "Compressor Pedal",
    "EQ Pedal",
    "Looper Pedal",
    "Wah Pedal",
    "Volume Pedal",
    "Power Supply",
    "Guitar Stand",
    "Guitar Strap",
    "Patch Cables",
    "Capo",
    "Guitar Picks",
    "Slide",
    "String Winder",
    "Pedalboard Case",
    "Pickguard",
    "Locking Tuners",
    "Nut Lubricant",
    "Pedal Switcher",
    "Noise Gate Pedal",
    "Octaver Pedal",
    "Boost Pedal",
    "ABY Switch",
    "Metronome",
    "Clip Tuner"
];